### ISSUE TITLE
Graphclient generates unknown type `DocumentNode`

### ISSUE THREAD

**Issue by wanglonghong** [graphprotocol/graph-client#60]
### Error details

File: .graphclient/index.ts
error: Parameter 'doc' of exported function has or is using private name 'DocumentNode'.ts(4078)

```
export async function getBuiltGraphSDK<TGlobalContext = any, TOperationContext = any>(globalContext?: TGlobalContext) {
  const { sdkRequesterFactory } = await getBuiltGraphClient();
  return getSdk<TOperationContext>(sdkRequesterFactory(globalContext));
}

export type Requester<C = {}> = <R, V>(doc: **_DocumentNode_**, vars?: V, options?: C) => Promise<R>;
export function getSdk<C>(requester: Requester<C>) {
  return {};
}
export type Sdk = ReturnType<typeof getSdk>;
```

### How to reproduce the above issue?

Its so simple. just to run the following script. `graphclient build --tsOnly`. This command generates typescript files but also generates unknown type => `DocumentNode`. This type throws when trying to build the typescript project using `tsc --build ./tsconfig.build.json` 

### Temporary Fix 
If I replace DocumentNode with `any` after graphclient build, typescript build works. but it is not a preferrable way. 
Is there a way to fix this when running `graphclient build --tsOnly`

Thanks

**Comment by dotansimha** [comment]
@ardatan what do you think?

**Comment by ardatan** [comment]
I need a reproduction because I've never seen this kind of error in our example :/

**Comment by dotansimha** [comment]
> I need a reproduction because I've never seen this kind of error in our example :/

I think I saw this issue in older versions, probably `0.0.3` and it was fixed already in Mesh. Should be fine. Let's wait for @wanglonghong 's update on that. `0.0.6` should fix that.

**Comment by wanglonghong** [comment]
@dotansimha. already tried with `0.0.6` but it still generates an unknown `DocumentNode` type.

**Comment by wanglonghong** [comment]
```
import {
  GraphQLResolveInfo,
  SelectionSetNode,
  FieldNode,
  GraphQLScalarType,
  GraphQLScalarTypeConfig,
} from "graphql";
```

I think this is the right position where we have to import `DocumentNode`. because `DocumentNode` is already defined in `graphql` package

**Comment by ardatan** [comment]
I have to reproduce it by myself with bunch of trial and errors because you didn't provide one :) So `DocumentNode` import is missing only if you don't have any documents defined in the configuration. Until this gets fixed, you can provide some as a workaround.

**Comment by wanglonghong** [comment]
Thanks @ardatan . yeah, I didn't have any documents defined in the configuration. Ok. I follow up your temporary fix and will make sure to help you to debug faster.

**Comment by ardatan** [comment]
Could you try with the latest versions? It should be fixed with the latest release.

**Comment by wanglonghong** [comment]
I think it is still the same if I upgraded the version properly. 
I created an action in the same repo. (https://github.com/wanglonghong/graphclient-test)
you can see the logs here.
https://github.com/wanglonghong/graphclient-test/runs/6573271048?check_suite_focus=tru

**Comment by dotansimha** [comment]
This should be fine now with 0.0.11. Another workaround to avoid this issue is to make sure to add any GraphQL query, even as dummy one like `query dummy { __typename }`.
